### ISSUE TITLE
Unreal Engine Fails to download with MD-DL

### ISSUE THREAD

**Issue by CanisHelix** [lancachenet/monolithic#108]
### Describe the issue you are having
Since implementing the monolithic cache I am unable to download Unreal Engine 4.23.4 (and probably other versions)

### How are you running the container(s)
```
version: '2'
services:
#  dns:
#    image: lancachenet/lancache-dns:latest
#    env_file: .env
#    restart: unless-stopped
#    ports:
#      - ${DNS_BIND_IP}:53:53/udp
  sniproxy:
    image: lancachenet/sniproxy:latest
    env_file: .env
#    restart: unless-stopped
    ports:
      - 443:443/tcp
  monolithic:
    image: lancachenet/monolithic:latest
    env_file: .env
#    restart: unless-stopped
    ports:
      - 80:80/tcp
    volumes:
      - ${CACHE_ROOT}/cache:/data/cache
      - ${CACHE_ROOT}/logs:/data/logs
```
### DNS Configuration

I have put the following in my `/var/unbound/conf.d/` folder on pfSense and I'm including `/var/unbond/conf.d/*.conf`

```
server:
  local-zone: "epicgames-download1.akamaized.net" redirect
  local-data: "epicgames-download1.akamaized.net 30 IN A 10.25.0.201"
  local-zone: "download.epicgames.com" redirect
  local-data: "download.epicgames.com 30 IN A 10.25.0.201"
  local-zone: "download2.epicgames.com" redirect
  local-data: "download2.epicgames.com 30 IN A 10.25.0.201"
  local-zone: "download3.epicgames.com" redirect
  local-data: "download3.epicgames.com 30 IN A 10.25.0.201"
  local-zone: "download4.epicgames.com" redirect
  local-data: "download4.epicgames.com 30 IN A 10.25.0.201"
```
