### ISSUE TITLE
Missing images and videos on various launchers

### ISSUE THREAD

**Issue by Themicles** [lancachenet/monolithic#134]
### Describe the issue you are having
Reinstalled my Lancache yesterday to switch to the docker-compose method. Caching games/updates, and Windows updates is working great. In fact, caching from Epic wasn't working before, but now is. However, both Epic and Steam are missing some images and some videos when browsing their stores or other embedded pages.
### How are you running the container(s)

```
version: '2'
services:
  dns:
    image: lancachenet/lancache-dns:latest
    env_file: .env
#    restart: unless-stopped
    ports:
      - ${DNS_BIND_IP}:53:53/udp
      - ${DNS_BIND_IP}:53:53/tcp

## HTTPS requests are now handled in monolithic directly
## you could choose to return to sniproxy if desired
#
#  sniproxy:
#    image: lancachenet/sniproxy:latest
#    env_file: .env
#    restart: unless-stopped
#    ports:
#      - 443:443/tcp

  monolithic:
    image: lancachenet/monolithic:latest
    env_file: .env
#    restart: unless-stopped
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - ${CACHE_ROOT}/cache:/data/cache
      - ${CACHE_ROOT}/logs:/data/logs

```

### DNS Configuration

```
Clients are given the address of the Lancache server as their only DNS server. Lancache DNS is set to forward to my router's DNS.
```

### Output of container(s)

```
No output that I can see of any use. Misses and hits but none appear to be identifiable are image requests and unless I'm missing something, I don't see any logging of forwarded HTTPS calls...
```
