### ISSUE TITLE
Download Speed dropping after a couple of seconds

### ISSUE THREAD

**Issue by sn1ce** [lancachenet/monolithic#162]
### Describe the issue you are having
After a couple of seconds (around 3-4 sec.) steams downloadrate drops to 0 Kb/s and after again some secs., it goes up to around 10-20% auf my actual download speed

### How are you running the container(s)

```
version: '3'
services:
  monolithic:
    container_name: monolithic
    image: lancachenet/monolithic:latest
    ports:
      - "80:80"
    volumes:
      - /home/lanserver/nvme/lancache/data:/data/cache
      - /home/lanserver/nvme/lancache/logs:/data/logs
    environment:
      - CACHE_MEM_SIZE=2500m
    restart: always
```

### DNS Configuration

```
  lancachedns:
    container_name: lancachedns
    image: lancachenet/lancache-dns:latest
    ports:
      - "10.0.0.167:53:53/udp"
    environment:
      - USE_GENERIC_CACHE=true
      - LANCACHE_IP=10.0.0.167
    restart: always
  sniproxy:
    container_name: sniproxy
    image: lancachenet/sniproxy:latest
    ports:
      - "443:443"
    restart: always
```

### Output of container(s)

```
server {

# Internal bind on 3128, this should not be externally mapped
listen localhost:3128 reuseport;

# No access_log tracking as all requests to this instance are already logged through monolithic

# access_log /data/logs/upstream-access.log cachelog;
error_log /data/logs/upstream-error.log;

# Including /etc/nginx/sites-available/upstream.conf.d/10_resolver.conf
resolver 8.8.8.8 8.8.4.4 ipv6=off;

# Finished including /etc/nginx/sites-available/upstream.conf.d/10_resolver.conf
# Including /etc/nginx/sites-available/upstream.conf.d/20_tracking.conf
# Header to track if resolved from upstream or 302 redirect
set $orig_loc 'upstream';
# Finished including /etc/nginx/sites-available/upstream.conf.d/20_tracking.conf
# Including /etc/nginx/sites-available/upstream.conf.d/30_primary_proxy.conf
# Proxy all requests to upstream
location / {
# Simple proxy the request
proxy_pass http://$host$request_uri;

# Catch the errors to process the redirects
proxy_intercept_errors on;
error_page 301 302 307 = @upstream_redirect;
}
# Finished including /etc/nginx/sites-available/upstream.conf.d/30_primary_proxy.conf
# Including /etc/nginx/sites-available/upstream.conf.d/40_redirect_proxy.conf
# Special location block to handle 302 redirects
location @upstream_redirect {
# Upstream_http_location contains the Location: redirection from the upstream server
set $saved_upstream_location '$upstream_http_location';

# Set debug header
set $orig_loc 'upstream-302';

# Pass to proxy and reproxy the request
proxy_pass $saved_upstream_location;
}
# Finished including /etc/nginx/sites-available/upstream.conf.d/40_redirect_proxy.conf
}
# Finished including /etc/nginx/sites-enabled/20_upstream.conf
}


stream {
# Including /etc/nginx/stream.d/log_format.conf
log_format stream_basic '$remote_addr [$time_local] $protocol $status $ssl_preread_server_name $bytes_sent $bytes_received $session_time';
# Finished including /etc/nginx/stream.d/log_format.conf
# Including /etc/nginx/stream-enabled/10_sni.conf
server {
listen 443;
resolver 8.8.8.8 8.8.4.4 ipv6=off;
proxy_pass $ssl_preread_server_name:443;
ssl_preread on;

access_log /data/logs/stream-access.log stream_basic;
error_log /data/logs/stream-error.log;
}
# Finished including /etc/nginx/stream-enabled/10_sni.conf
}

# Finished including /etc/nginx/nginx.conf
Checking nginx config
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
Config check successful
Starting Supervisord
```

Hi there, first of all, thanks for providing this lancache, pretty cool.

I want to mention, that i want to use it for small lanparty, and even for my own use.

My Lanserver is connected to a USB3.0 to 2.5GBE Adapter -> 2.5GBit Switch -> Gaming PC with 2.5Gbit.

When I download a cached game, e.g. Left 4 dead, it is hitting the full speed for a couple of seconds, then it drops to zero, and after that it goes up to around 50-60 mb/s. 

I can remember on my last Lanparty, i had "only" 1 Gbit, and this was working pretty well without any issues. I checked my USB Adapter, but this seems to run fine with iperf3 and iperf1. 

My specs for the Lanserver are:

Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
12 GB RAM (since one died yesterday) will change this
1 TB NVME PCIe - speeds are as expectet around 3Gbit

Help is appreciated :)

Many thanks!
