### ISSUE TITLE
(LXC) Stuck at "Starting Supervisord"

### ISSUE THREAD

**Issue by gpago** [lancachenet/monolithic#165]
### Describe the issue you are having
I'm running Lancache on an Ubuntu 20.04 LXC, with Proxmox 7.3 being the hypervisor.
It's been running fine for the last 1.5-2years, and updating between minor Proxmox versions was never an issue.
But ~2weeks ago, I updated a few packages on the host and after restarting, Lancache would just get stuck at "Starting Supervisord".
I looked at the processes with `strace` and I can see the nginx cache loader [going through seemingly reading every cached file](https://imgur.com/a/NhPEhUD.png).

- Apart from cache location and IPs, all other values are the default.  
- Updating to the latest Lancache docker image did not change anything. Creating a new LXC with Lancache, resulted in the same behavior.
- Size increase delta for the last 4-5months has been 20-30GB and is way below the limit.
- Cache data is on a hard drive (speed test with `dd` and `fio` was fine).
- Cache directory and file have all permissions and owner is `www-data` or userId 33 in the LXC and docker container (had issues with that before)

I know this seems more a compatibility issue, but I thought I'd try to see if anyone else has/had this issue.
Thank you in advance!

### How are you running the container(s)

```
version: '2'
services:
  dns:
    image: lancachenet/lancache-dns:latest
    env_file: .env
    restart: unless-stopped
    ports:
      - ${DNS_BIND_IP}:53:53/udp
      - ${DNS_BIND_IP}:53:53/tcp
  monolithic:
    image: lancachenet/monolithic:latest
    env_file: .env
    restart: unless-stopped
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - ${CACHE_ROOT}/cache:/data/cache
      - ${CACHE_ROOT}/logs:/data/logs
```

### DNS Configuration

```
DNS is handled by Adguard Home which uses Lancache as its upstream.
```

### Output of container(s)

```
...
monolithic_1  | Checking nginx config
monolithic_1  | nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
monolithic_1  | nginx: configuration file /etc/nginx/nginx.conf test is successful
monolithic_1  | Config check successful
monolithic_1  | Starting Supervisord
```
