### ISSUE TITLE
Only getting 40Mbit-ish on initial caching

### ISSUE THREAD

**Issue by BenWoodford** [lancachenet/monolithic#50]
### Describe the issue you are having
Admittedly I am still on the old steamcache-steam container, but before I go through the process of updating I wanted to see if I was missing something first.

Speeds when downloading a cached game are great. Easy 500Mbps when it gets up to speed. However, the initial speeds I'm getting for an uncached game on our 750Mbit line are a mere 45Mbit. Which isn't ideal.

I'd like to not kill steamcache, as it will be useful to have in the office (albeit it's a small team), so I'd like to try and resolve that one.

Is this just a case of write speeds not being sufficient, or should they not affect the speed of the download?

### How are you running the container(s)?
```
version: '2'
services:
 steamcache-steam:
   container_name: steamcache-steam
   hostname: steam.cache.domain.ext
   image: steamcache/steamcache:latest
   restart: unless-stopped
   volumes:
     - "/mnt/filestore/caches/steam/:/data/cache"
     - "/mnt/filestore/logs/caches/steam:/data/logs"
   ports:
     - '80:80'
   environment:
     - TZ=Europe/London
   networks:
     default:
       ipv4_address: 10.10.3.1
networks:
  default:
    external:
      name: macvlan-nat
```

### DNS Configuration
```
version: '2'
services:
 steamcache-dns:
   container_name: steamcache-dns
   image: steamcache/steamcache-dns:latest
   restart: unless-stopped
   environment:
     - TZ=Europe/London
     - UPSTREAM_DNS=8.8.8.8
     - STEAMCACHE_IP=10.10.3.1
   networks:
     default:
       ipv4_address: 10.10.1.2
networks:
  default:
    external:
      name: macvlan-nat
```
