### ISSUE TITLE
IPv6

### ISSUE THREAD

**Issue by zamatscha** [lancachenet/monolithic#53]
We're had problems setting this hole thing up, till we disabled the ipv6 in the windows clients for dns.

We suggest an FAQ or a hint on the install instructions that people should disable their ipv6 on clients?!

Thanks for lancache!

**Comment by Candunc** [comment]
Docker doesn't support dual stack network (At least the last time I looked into this issue) so you must either disable IPv6 DNS lookup or manually set up an IPv6 DNS server with the proper domains forwarded.

In lieu of IPv6 support I agree there should be a note to disable IPv6 DNS lookup on the clients, even if it's implicitly made obvious by `echo Please configure your router/dhcp server to serve dns as $HOST_IP` in the example script.

**Comment by GotenXiao** [comment]
One way to achieve dual-stack IPv4/IPv6 support when using Docker is to use the `macvlan` network driver.

As an example in `docker-compose` syntax:
```yaml
version: '2.3'

services:
  # this service is simply here as an anchor for the networks
  hodor:
    image: tianon/true
    restart: no
    networks:
      vlan8:

networks:
  vlan8:
    name: vlan8
    driver: macvlan
    driver_opts:
      # the dotted suffix here is a VLAN identifier
      # you can also specify the exact name of a host interface
      parent: enp1s0.8 
    enable_ipv6: true
    ipam:
      config:
        - subnet: 10.255.255.0/24
          # the gateway address must be a router on this subnet
          gateway: 10.255.255.1
          # this will result in 10.255.255.64 - 10.255.255.127 being available in the IP pool for containers
          ip_range: 10.255.255.64/26
        - subnet: '2001:db8:6c61:6e::/64'
          gateway: '2001:db8:6c61:6e::1'
          # this will result in 2001:0db8:6c61:6e:1:: - 2001:0db8:6c61:6e:1:ffff:ffff:ffff being in the pool
          ip_range: '2001:db8:6c61:6e:1::/80'  
```

I'd generally advise manually creating the network using `docker network create` however.
